### ISSUE TITLE
About connected_slave_lag_seconds metric

### ISSUE THREAD

**Issue by rizkymma** [RocksLabs/kvrocks_exporter#30]
Hi,

According to https://github.com/apache/kvrocks/discussions/1504, it was not actually 'seconds' but it represents the write sequence gap.
 
Could someone confirm this?

https://github.com/RocksLabs/kvrocks_exporter/blob/013564909cb969fcd3c44a080d7f320cc6ad5796/exporter/info.go#L240

Thanks.

**Comment by git-hulk** [comment]
@rizkymma Yes, you're right. The `connected_slave_lag_seconds` represents the gap of the write sequence if Kvrocks.

**Comment by rizkymma** [comment]
Got it, thanks
