### ISSUE TITLE
Build Docker image with release tags/versions

### ISSUE THREAD

**Issue by kinoute** [RocksLabs/kvrocks_exporter#33]
It would be nice if the Docker image on the Hub could follow the "releases" tags available here (1.0.1 at the time of writing). Right now there is only one tag, "latest".

Thanks!

**Comment by git-hulk** [comment]
@kinoute Yes, I push a new tag 1.0.2 manually for the latest tag and it'd be better to create a tag while pushing the new tag.

**Comment by evolvedlight** [comment]
I've created https://github.com/RocksLabs/kvrocks_exporter/pull/40 which should address this

**Comment by git-hulk** [comment]
@evolvedlight Yes, thanks for your great contribution.
