### ISSUE TITLE
No golang build in the actions?

### ISSUE THREAD

**Issue by evolvedlight** [RocksLabs/kvrocks_exporter#35]
**Describe the problem**
It'd be nice to be able to download the binary from the releases

**Running the exporter**
It's a pain! I had to compile it myself

**Question**
Would you accept a PR that would add a binary build into the actions? Or some sort of release process?

**Comment by git-hulk** [comment]
@evolvedlight Sorry for the late reply. It sounds good to me, PR is always welcome.

**Comment by evolvedlight** [comment]
Thanks!

**Comment by evolvedlight** [comment]
Thanks @git-hulk , looks like it's working as expected now.
